### ISSUE TITLE
no sharding atoms found for glob pattern hits*.parquet

### ISSUE THREAD

**Issue by enricorotundo** [davidgasquez/cod-playground#4]
```
❯ bacalhau version
Client Version: v0.3.16
Server Version: v0.3.16
❯ bacalhau create bacalhau/shared_duckdb.yaml --download
Error executing job: failed to submit job: publicapi: after posting request: error generating execution plan: no sharding atoms found for glob pattern hits*.parquet
```

**Comment by davidgasquez** [comment]
Heya @enricorotundo, any tips/ideas on how to work around this one?

**Comment by enricorotundo** [comment]
I believe the job yaml structure was outdated and we did not output a clear error message, the following one works 😃 :
```yaml
APIVersion: V1beta1
Spec:
    Engine: Docker
    Docker:
        Image: davidgasquez/duckdb:latest
        WorkingDirectory: /inputs
        Entrypoint:
            - duckdb
            - -s
            - "select count(*) from '*.parquet'"
    Timeout: 3600
    Sharding:
      BatchSize: 3
      GlobPattern: /*
      BasePath: /inputs
    Inputs:
        - StorageSource: URLDownload
          URL: https://datasets.clickhouse.com/hits_compatible/athena_partitioned/hits_1.parquet
          Path: /inputs
        - StorageSource: URLDownload
          URL: https://datasets.clickhouse.com/hits_compatible/athena_partitioned/hits_2.parquet
          Path: /inputs
        - StorageSource: URLDownload
          URL: https://datasets.clickhouse.com/hits_compatible/athena_partitioned/hits_3.parquet
          Path: /inputs
    Outputs:
        - Name: outputs
          Path: /outputs
    Deal:
        Concurrency: 1
```

For reference, I've just updated the above by looking at the current struct (we're on v0.3.17 now): https://github.com/filecoin-project/bacalhau/blob/1d59bf46660ee6c1f993ad8cb0eea9a382e8e5b3/pkg/model/job.go

```
❯ bacalhau create shared_duckdb.yaml --download
Job successfully submitted. Job ID: 1486d897-6927-48bd-bfc6-51a26df04978
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

	    Communicating with the network  ................ done ✅  0.0s
	       Creating job for submission  ................ done ✅  0.0s
	       Finding node(s) for the job  ................ done ✅  0.0s
	                   Running the job  ................ done ✅  15.6s
	   Job finished, verifying results  ................ done ✅  15.6s
	                   Running the job  ................ done ✅  15.6s

To download the results, execute:
  bacalhau get 1486d897-6927-48bd-bfc6-51a26df04978

To get more details about the run, execute:
  bacalhau describe 1486d897-6927-48bd-bfc6-51a26df04978
Fetching results of job '1486d897-6927-48bd-bfc6-51a26df04978'...
Results for job '1486d897-6927-48bd-bfc6-51a26df04978' have been written to...
/Users/enricorotundo/winderresearch/ProtocolLabs/cod-playground/bacalhau/job-1486d897
```
